-- =============================================================
-- MQ Digital Platform — 0002 (MySQL) — registry nilai domain
-- Asal: PostgreSQL 0002 enums (CREATE TYPE ... AS ENUM).
-- MySQL: nilai enum PG di-inline menjadi VARCHAR + CHECK pada tabel
--        (lihat masing-masing file tabel). File ini = DOKUMENTASI
--        pusat nilai yang valid (jangan lupa sinkron CHECK saat menambah).
-- Daftar domain (kolom VARCHAR(...) + CHECK di tabel):
--   account_type          SANTRI,UMUM,PENGURUS,ORANG_TUA,DONATUR
--   user_status           PENDING_VERIFICATION,ACTIVE,SUSPENDED,DEACTIVATED,DELETED*
--   gender                MALE,FEMALE
--   device_platform       ANDROID,IOS,WEB
--   media_kind            AUDIO,IMAGE,VIDEO,DOCUMENT
--   media_status          UPLOADING,READY,FAILED
--   submission_status     PENDING,IN_REVIEW,PASSED,REVISION,REJECTED
--   review_verdict        PASSED,REVISION,REJECTED
--   campaign_mode         PARALLEL,SEQUENTIAL
--   campaign_status       DRAFT,SCHEDULED,ACTIVE,COMPLETED,CANCELLED
--   juz_status            ASSIGNED,IN_PROGRESS,COMPLETED,EXPIRED,REASSIGNED
--   verification_status   PENDING,AUTO_VERIFIED,VERIFIED,REJECTED
--   question_status       PENDING_MODERATION,QUEUED,ASSIGNED,ANSWERED,CLOSED,REJECTED,PUBLISHED,PUBLISH_REQUESTED*
--   message_type          TEXT,VOICE,IMAGE,FILE
--   ustadz_assignment_status ASSIGNED,ACCEPTED,DECLINED,REASSIGNED
--   notification_channel  IN_APP,PUSH,EMAIL,WHATSAPP
--   material_status       DRAFT,PUBLISHED,ARCHIVED
--   article_status        DRAFT,PUBLISHED,ARCHIVED
--   banner_position       HOME_TOP,HOME_MID,KHOTMIL_TOP
--   announcement_level    INFO,WARNING,CRITICAL
--   job_status            PENDING,RUNNING,DONE,FAILED,DEAD
-- (*penambahan v11: DELETED utk delete-account; PUBLISH_REQUESTED utk moderation state machine)
-- =============================================================

-- no-op (nilai di-CHECK per tabel)
