-- =============================================================
-- MQ Digital Platform — 0006b (MySQL) quran_words v2 (Task 1.2 v8)
-- Ekspansi kolom WBW: transliteration + text_en.
-- NO-OP sejak deploy prod (2 Okt 2026): definisi final kolom transliteration
-- + text_en SUDAH ada di file 0006 utama (CREATE TABLE utk fresh install),
-- sehingga file ini hanya berlaku utk instance dev/test historis yang sudah
-- apply versi awal 0006 (di sana sudah tercatat di _mq_migration).
-- Menjalankan ulang ALTER di fresh install = duplicate column error.
-- =============================================================

-- no-op (definisi final di 0006)
